### ISSUE TITLE
Works but slow!

### ISSUE THREAD

**Issue by C0DE4ME** [rssnyder/discord-stock-ticker#1]
Hello the bots are great, simple & easy!
However, its custom status market price doesn't change often. : (
Im aware its name changes only once an hour due to discords restrictions, but the custom status seems to get hung up a lot (as much as 30 minutes behind real time prices).
Would self hosting it make it better?

Anyways people in my server love the bots keep at it!!

**Comment by rssnyder** [comment]
Thanks for the feedback!

I did push some changes to the bots earlier today that made them a bit quicker and made the statuses more clear.

I will take look at what I can do to get some metrics to see where I can speed things up.

**Comment by C0DE4ME** [comment]
wow blazing fast reply.
thank you!

**Comment by rssnyder** [comment]
@C0DE4ME I just added logging and hooked my application stack up to grafana using loki + promtail. Tomorrow if you notice it is behind again please let me know what ticker seems to be lagging, I should now be able to investigate or even be proactive in fixing any issues. 

Feel free to open this issue back up or find me on discord (username in readme) if problems keep happening.

**Comment by C0DE4ME** [comment]
thank you, seems to be working much better now!
