### ISSUE TITLE
[HELP] loading previous tickers without redis server?

### ISSUE THREAD

**Issue by kakigorimochi** [rssnyder/discord-stock-ticker#105]
As the title suggests, is there a way to load or save previously set tickers?

I always need to re-configure the tickers whenever I reboot my VPS. 
I saw the "-db" feature but don't actually know how the feature works.

I am currently running CENTOS 7 as my Operating System.

**Comment by rssnyder** [comment]
From the readme:
`  -db="" # file to store tickers in`

**Comment by kakigorimochi** [comment]
> From the readme: ` -db="" # file to store tickers in`

sorry, but I am not sure what kind of file type it takes in. Is it an actual ".db" file? I am not sure how do I make one. 

I even tried .txt and hope it would work. Sadly, I already knew it wouldn't, although it was worth a shot. haha

**Comment by rssnyder** [comment]
> > From the readme: ` -db="" # file to store tickers in`
> 
> sorry, but I am not sure what kind of file type it takes in. Is it an actual ".db" file? I am not sure how do I make one.
> 
> I even tried .txt and hope it would work. Sadly, I already knew it wouldn't, although it was worth a shot. haha

just put any file name there, it will create a new file and make it an sqlite3 db. **dont** use an existing filename.

**Comment by kakigorimochi** [comment]
Can I assign/load the DB file in another directory or does it have to be in the same directory?

**Comment by rssnyder** [comment]
> Can I assign/load the DB file in another directory or does it have to be in the same directory?

it can be anywhere

**Comment by kakigorimochi** [comment]
> > Can I assign/load the DB file in another directory or does it have to be in the same directory?
> 
> it can be anywhere

Thank you for your response because for some reason CENTOS 7 likes to count the quotes ("") as part of the name file that's why I get the error: "**Unable to bootstrap db file: unable to open database file: not a directory**" for the **-db=""** flag. 

I tried removing the said quotes ("") in the discord-stock-ticker.service file and it finally worked.


Doesn't work for CENTOS 7
`ExecStart = ./discord-stock-ticker -frequency=10 -db="./discord-stock-ticker/directory/filename"`

Works for CENTOS 7
`ExecStart = ./discord-stock-ticker -frequency=10 -db=./discord-stock-ticker/directory/filename`
