### ISSUE TITLE
[NEW STOCK] I suggest add a bot for the Gala (GALA).

### ISSUE THREAD

**Issue by LArtDesChOiX** [rssnyder/discord-stock-ticker#107]
Hiii, thanks for all yur bor ;)

if I can allow myself a suggestion, it would be to add the gala please! : D 
https://coinmarketcap.com/fr/currencies/gala/

Thanks, see yu.

**Comment by rssnyder** [comment]
I am not making more free bots, but you can host your own version using the code in this repo.

**Comment by LArtDesChOiX** [comment]
Ok, thanks for the info. I will try later :D
