### ISSUE TITLE
[BUG] Docker - 401 Discord

### ISSUE THREAD

**Issue by Gildraen** [rssnyder/discord-stock-ticker#129]
**Describe the bug**
Hi, i can't add any ticker/gas or other with docker i always have a 401, and it seems this prevent me to delete it after too

**To Reproduce**
1. Run a docker-compose up with compose file provided in the doc
2. Post a new ticker
3. First error 401

![image](https://user-images.githubusercontent.com/20871857/150108990-d6db8905-d8db-4a58-97b3-5f63529df650.png)

5. Try to Delete any bot
6. The app stop and can't send any more request, the bot does not delete

**Expected behaviour**
Connection to discord and deletion possible

**Python (please complete the following information):**
 - docker desktop 4.4.3 (73365) 
 - OS Windows 11

**Comment by rssnyder** [comment]
The unable to delete is a known bug.

The 401 error is because your discord token is invalid. Regenerate a new one and try again.
