### ISSUE TITLE
TICKER BOT unable to change nickname

### ISSUE THREAD

**Issue by LondonRu3k** [rssnyder/discord-stock-ticker#131]
**Describe the bug**
Bot when added to discord server with correct permission is unable to update its own nicknames

ERRO[0961] Updating nickname: HTTP 404 Not Found, {"message": "Unknown Member", "code": 10007} 
DEBU[0961] Set activity: -0.89 (-14.70%)                
DEBU[0961] Fetching crypto price for looksrare          
DEBU[0961] Set nickname in The Rueks Twitch Community: LOOKS \u2b0a $5.15 
ERRO[0971] Updating nickname: HTTP 404 Not Found, {"message": "Unknown Member", "code": 10007} 
DEBU[0971] Set activity: -0.89 (-14.70%)                
DEBU[0971] Fetching crypto price for looksrare          
DEBU[0972] Set nickname in The Rueks Twitch Community: LOOKS \u2b0a $5.15 
ERRO[0982] Updating nickname: HTTP 404 Not Found, {"message": "Unknown Member", "code": 10007} 
DEBU[0982] Set activity: -0.89 (-14.70%)                
DEBU[0982] Fetching crypto price for looksrare          
DEBU[0982] Set nickname in The Rueks Twitch Community: LOOKS \u2b0a $5.15 
ERRO[0992] Updating nickname: HTTP 404 Not Found, {"message": "Unknown Member", "code": 10007} 

Works on all other servers except one.

**Comment by rssnyder** [comment]
I'm not exactly sure how, but the first troubleshooting step that comes to my head is "_show me_ that the permissions on the servers are the same".

Next, the error says **404 Not found: Unknown Member**, which makes me think it can't get its own user status from the server. Can you make sure the bot's permissions in the server allow it to see itself? Is that a thing?

This isn't really code related, so I'm not sure what other help I can offer. Join the discord server and ping me in #general if you want to chat there.
