### ISSUE TITLE
Bot in multiple discord server

### ISSUE THREAD

**Issue by giga89** [rssnyder/discord-stock-ticker#136]
Hi, I have done my first bot with your fantastic work.
But I have a problem. I have included my bot in two server but only in first one change..
Which could be the problem?

![image](https://user-images.githubusercontent.com/1588412/151028432-dfcecd50-20c4-4f8b-b1c2-49499fdb072c.png)

![image](https://user-images.githubusercontent.com/1588412/151028499-73515c60-d55e-4dd0-a26a-d3c837f07484.png)

I try in a third server and I have the same issue..

**Comment by rssnyder** [comment]
you have to restart the service every time a bot is addded to a new server.

**Comment by giga89** [comment]
RIGHT!
Thank u so much.
Have a nice day
