### ISSUE TITLE
Save ticker on db

### ISSUE THREAD

**Issue by oncerist** [rssnyder/discord-stock-ticker#137]
I'm currently still learning linux so I'm not that familiar yet. I wanted to ask how will i add the -db setting so that I can save the tickers that I created. 

I use this btw and I'm using a vps

```
wget https://github.com/rssnyder/discord-stock-ticker/releases/download/v3.3.0/discord-stock-ticker-v3.3.0-linux-amd64.tar.gz

tar zxf discord-stock-ticker-v3.3.0-linux-amd64.tar.gz

mkdir -p /etc/discord-stock-ticker

mv discord-stock-ticker /etc/discord-stock-ticker/

wget https://raw.githubusercontent.com/rssnyder/discord-stock-ticker/master/discord-stock-ticker.service

mv discord-stock-ticker.service /etc/systemd/system/

systemctl daemon-reload

systemctl start discord-stock-ticker.service
```

**Comment by rssnyder** [comment]
Edit the service file so it has the flags you need.

**Comment by oncerist** [comment]
![IMG_20220127_214549](https://user-images.githubusercontent.com/62338866/151371159-9347bfe0-f133-41c3-a5dd-87333cf17fd9.jpg)
Like this?

**Comment by rssnyder** [comment]
yes but, the path for your db looks wrong, just make it `-db=./discordbottickers.db`

**Comment by oncerist** [comment]
Thanks. Do I have to stop the bot and make the tickers again or will this save the tickers that I have already?

**Comment by rssnyder** [comment]
> Thanks. Do I have to stop the bot and make the tickers again or will this save the tickers that I have already?

be sure and do `systemctl daemon-reload` after every change to the systemd file, otherwise the changes wont take affect.

once the service has been started with the `-db` flag, any bots added will be stored in the DB. If you have bots running now added before you added the flag, they will need to be created again after restarting the service with the flag.

you can verify the DB is being using if you see this log line when you start the service `INFO[0000] Will be storing state in ./discordbottickers.db `

you can see logs with `journalctl -f -u discord-stock-ticker`

**Comment by oncerist** [comment]
Thank you very much for this

**Comment by rssnyder** [comment]
> Thank you very much for this

Anytime! I think the best way to make documentation is just to write stuff down when you teach someone new. https://github.com/rssnyder/discord-stock-ticker/commit/9740d88810dd8e1d5d48c1185627439a3e482192

**Comment by oncerist** [comment]
![IMG_20220128_093525](https://user-images.githubusercontent.com/62338866/151471809-79829975-1fec-42db-afb7-1dce1826e1f5.jpg)

Is this correct?

**Comment by rssnyder** [comment]
you must have an error in your systemd file, share it here and ill take a look.

**Comment by oncerist** [comment]
> you must have an error in your systemd file, share it here and ill take a look.

![IMG_20220128_100845](https://user-images.githubusercontent.com/62338866/151474908-b6d02626-f113-42bd-972e-d3603916e2a4.jpg)
Here

I use
systemctl edit discord-stock-ticker.service
To edit

**Comment by rssnyder** [comment]
that isnt my template, what you should have is:

https://github.com/rssnyder/discord-stock-ticker/blob/master/discord-stock-ticker.service

```
[Unit]
Description=discord-stock-ticker
Wants=basic.target
After=basic.target network.target
Before=sshd.service

[Service]
SyslogIdentifier=discord-stock-ticker
StandardOutput=syslog
StandardError=syslog
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/etc/discord-stock-ticker/discord-stock-ticker -db=./discordbottickers.db
Restart=always

[Install]
WantedBy=multi-user.target

```

**Comment by oncerist** [comment]
Will the db file create itself or do I have to make one first?

**Comment by rssnyder** [comment]
> 

**do not create it first** it will create the file itself.

**Comment by a11verklempt** [comment]
I receive an error that states my flag -db is provided, but not defined.

flag provided but not defined: -db
Usage of ./discord-stock-ticker:
  -address string
        address:port to bind http server to. (default "localhost:8080")
  -cache
        enable cache for coingecko
  -logLevel int
        defines the log level. 0=production builds. 1=dev builds.
  -redisAddress string
        address:port for redis server. (default "localhost:6379")

**Comment by a11verklempt** [comment]
> ![IMG_20220128_104318](https://user-images.githubusercontent.com/62338866/151478231-e682f648-936e-46fd-8a11-66dd05111f14.jpg) I got another error
> 
> ![IMG_20220128_104332](https://user-images.githubusercontent.com/62338866/151478279-7f0a79b0-990a-4d24-85a2-45cb775ea909.jpg) I just copied and pasted the one you sent.

I got the same error. When editing the file, it saves as a snippet, instead of overwriting the original. So, it runs both `discord-stock-ticker.service` and the edit you created. typically, `/etc/systemd/system/discord-stock-ticker.service.d/override.conf`

I've no idea how to fix this.
