### ISSUE TITLE
can't update color and nickname[BUG]

### ISSUE THREAD

**Issue by Merrick17** [rssnyder/discord-stock-ticker#139]
**Describe the bug**
i'm trying to add a new bot , however the result output shows false for both attributes.
 
![image](https://user-images.githubusercontent.com/25400839/154571027-a94cbcb0-ce65-4eeb-8a83-4a765e6b4dee.png)

**To Reproduce**

**Expected behaviour**

**Python (please complete the following information):**
 - Version: [e.g. 3.8]
 - OS [e.g. linux, windows]

**Additional context**

**Comment by rssnyder** [comment]
What version of the code are you running?

**Comment by Merrick17** [comment]
> What version of the code are you running?

discord-stock-ticker-v3.3.0-linux-amd64

**Comment by rssnyder** [comment]
Please update. The JSON keys you are using are correct for the current release but not the release you are using.
