### ISSUE TITLE
[BUG] Holder error

### ISSUE THREAD

**Issue by jmaxin07** [rssnyder/discord-stock-ticker#140]
I have been running Market cap and holder bots through your amazing repository for the last several months. Suddenly today my holder bot only displays "Holders" as its name where it should display just a number representing the amount of holders from etherscan. I did notice Etherscan has implemented a captcha on their site in the last few days and was wandering if this is something that needs fixed in an update or if there is something that can be done on my end. Thanks in advance! Also I am running this on linux

**Comment by rssnyder** [comment]
Yup. Holders scrapes so a captcha will break it. 

If you know where I can find holders via an API please share.
