### ISSUE TITLE
[BUG] Bots are unable to join server

### ISSUE THREAD

**Issue by jdoles** [rssnyder/discord-stock-ticker#148]
**Describe the bug**
An error message is displayed stating that the bot cannot join any more servers because it hasn't been verified.

**To Reproduce**
1. Go to crypto
2. Click on a currency
3. Complete authorization
![image](https://user-images.githubusercontent.com/5995756/166082995-eda34110-a6c9-46cf-ba00-7195b33eac09.png)

**Expected behaviour**
Bot should be able to join servers

**Comment by rssnyder** [comment]
Discord hasn't been verifying bots as of late, nothing we can do but wait. Join the discord to get notified of when they're verified.
