### ISSUE TITLE
[BUG] ETH Gas

### ISSUE THREAD

**Issue by radrach23** [rssnyder/discord-stock-ticker#153]
**Describe the bug**

ETH Gas price does not show in discord sidebar

**To Reproduce**
I am able to link it to the server but in the sidebar it does not show
![image](https://user-images.githubusercontent.com/55694744/170036689-a452c491-eacd-4071-9f00-4f67f540f420.png)

**Expected behaviour**
current ETH gas price would show

**Comment by rssnyder** [comment]
The API I was using is dead. I have yet to find another that is free. No ETA on fix.

**Comment by radrach23** [comment]
alright thank you
