### ISSUE TITLE
Anyone can help me? 

### ISSUE THREAD

**Issue by Mochikennedy** [rssnyder/discord-stock-ticker#156]
`--2022-06-08 09:28:46--  https://github.com/rssnyder/discord-stock-ticker/releases/download/v2.0.0/discord-stock-ticker-v3.3.0-linux-amd64.tar.gz
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-08 09:28:46 ERROR 404: Not Found.`

**Comment by rssnyder** [comment]
what is the command you are running that gives you this?
