### ISSUE TITLE
[BUG] - Floor ERRO[1627] Error getting floor rates: invalid character '<' looking for beginning of value 

### ISSUE THREAD

**Issue by cucuchiu** [rssnyder/discord-stock-ticker#163]
I've installed and ran the bot correctly on localhost 8080.

I've ran this command to track the magic eden floor price:
curl -X POST -H "Content-type: application/json" -d '{
  "marketplace": "magiceden",                         
  "name": "awf",                               
  "nickname": true,                                 
  "frequency": 10,                                  
  "discord_bot_token": "mytoken"   
}' localhost:8080/floor

the name is the label that I find in the magic eden url https://magiceden.io/marketplace/awf

After the command i get the following error ERRO[1627] Error getting floor rates: invalid character '<' looking for beginning of value

**Comment by rssnyder** [comment]
magiceden is not supported, it is in the readme by mistake.
