### ISSUE TITLE
Solanart floor bot show 0.00000

### ISSUE THREAD

**Issue by cucuchiu** [rssnyder/discord-stock-ticker#164]
I've configured solanart floor bot price for a collection:
curl -X POST -H "Content-type: application/json" -d '{"marketplace": "solanart", "name": "awf","nickname": true, "frequency": 10, "discord_bot_token": "mytoken"}' localhost:8080/floor

The bot works but show 0.00000 SOL and the real floor price is 0.087 SOL.

I've also tryed to delete it:  curl -X DELETE localhost:8080/floor/solanart-awf
but show this error: ERRO[1137] Error getting floor rates: unexpected end of JSON input 
ERRO[1144] Error getting floor rates: unexpected end of JSON input 
ERRO[1154] Error getting floor rates: unexpected end of JSON input 
ERRO[1164] Error getting floor rates: unexpected end of JSON input 

Thank you in advance.

**Comment by rssnyder** [comment]
Thanks for the issue! It looks like they changed APIs and I was able to track the corrected URL down! This will be in the next release.
![image](https://user-images.githubusercontent.com/7338312/196301416-ebb76c02-d666-44dc-9a70-0b776cef385b.png)

**Comment by rssnyder** [comment]
fixed in linked pr
