### ISSUE TITLE
[BUG] Ticker stop update

### ISSUE THREAD

**Issue by giga89** [rssnyder/discord-stock-ticker#177]
I have a ticker bot self hosted and from yesterday bot update is stuck.

This is json properties file:
```
{
  "name": "star-atlas-dao",
  "crypto": true,
  "ticker": "Polis",
  "color": true,
  "decimals": 4,
  "nickname": true,
  "frequency": 10,
  "discord_bot_token": "xxx"
}

```

I have tryied to restart 
```

systemctl stop discord-stock-ticker.service

systemctl start discord-stock-ticker.service

root@faccio-un-sacco-di-cose-SAI:~# curl -X POST -H "Content-type: application/json" -d @polis.json localhost:8080/ticker
{"ticker":"Polis","name":"star-atlas-dao","nickname":true,"frequency":10,"color":true,"decorator":"","currency":"usd","currency_symbol":"$","decimals":4,"activity":"","pair":"","pair_flip":false,"multiplier":1,"client_id":"935892618250948618","crypto":true,"discord_bot_token":"xxx":"","exrate":0}

```

but nothing happen. 
what am I doing wrong?

Thanks

**Comment by rssnyder** [comment]
The return JSON you have there makes it looks like the bot was successfully created.

Are you using the state file at all?

Can you turn on debug loggin `-logLevel=1` and paste the logs from service restart to about 30s after you make the curl call?

**Comment by giga89** [comment]
Where I have to put loglevel 1?  @rssnyder

**Comment by giga89** [comment]
INFO[0044] Added ticker: Polis                          
INFO[0045] Using usd                                    
INFO[0045] Watching crypto price for star-atlas-dao     
DEBU[0055] Fetching crypto price for star-atlas-dao     
ERRO[0055] Unable to fetch crypto price for star-atlas-dao: invalid character '<' looking for beginning of value 
DEBU[0065] Fetching crypto price for star-atlas-dao     
ERRO[0065] Unable to fetch crypto price for star-atlas-dao: invalid character '<' looking for beginning of value 
DEBU[0075] Fetching crypto price for star-atlas-dao     
ERRO[0075] Unable to fetch crypto price for star-atlas-dao: invalid character '<' looking for beginning of value

**Comment by giga89** [comment]
> The return JSON you have there makes it looks like the bot was successfully created.
> 
> Are you using the state file at all?
> 
> Can you turn on debug loggin `-logLevel=1` and paste the logs from service restart to about 30s after you make the curl call?

INFO[0044] Added ticker: Polis                          
INFO[0045] Using usd                                    
INFO[0045] Watching crypto price for star-atlas-dao     
DEBU[0055] Fetching crypto price for star-atlas-dao     
ERRO[0055] Unable to fetch crypto price for star-atlas-dao: invalid character '<' looking for beginning of value 
DEBU[0065] Fetching crypto price for star-atlas-dao     
ERRO[0065] Unable to fetch crypto price for star-atlas-dao: invalid character '<' looking for beginning of value 
DEBU[0075] Fetching crypto price for star-atlas-dao     
ERRO[0075] Unable to fetch crypto price for star-atlas-dao: invalid character '<' looking for beginning of value

**Comment by rssnyder** [comment]
That looks like an error with what coingecko is returning from the API calls. Are you being rate limited? Try resolving this page on the same server: https://api.coingecko.com/api/v3/coins/star-atlas-dao

**Comment by rssnyder** [comment]
That is very odd, but explains what is happening. You are for some reason/somehow being blocked from coingecko.
