### ISSUE TITLE
[BUG] Update docker-compose.yml file

### ISSUE THREAD

**Issue by 0x3639** [rssnyder/discord-stock-ticker#189]
Just wanted to let you know that the DB env variable in the docker-compose.yml section of this link below is not correct.

https://elements.heroku.com/buttons/rssnyder/discord-stock-ticker

`DB=/dst.db` should be `DB=./dst.db`

If you use `DB=/dst.db` you will get the following error.
```
time="2023-01-07T12:02:58Z" level=info msg="Running discord-stock-ticker version development..."
time="2023-01-07T12:02:58Z" level=error msg="Unable to bootstrap db file: unable to open database file: out of memory (14)\n"
time="2023-01-07T12:02:58Z" level=warning msg="Will not be storing state."
time="2023-01-07T12:02:58Z" level=info msg="Starting api server on 0.0.0.0:8080..."
```

**Comment by rssnyder** [comment]
@0x3639  I am not sure where heoku is getting the configuration from. If you can point me towards the source I can fix it.

**Comment by 0x3639** [comment]
I'm not 100% sure where it's coming from.  I assumed that you created it.  I followed the instructions and noticed the issue w/ the db path.  Maybe it's an old clone of github that stopped replicating?  Not sure.  I'll close this out for now.
