### ISSUE TITLE
[NEW Release] Create a new release

### ISSUE THREAD

**Issue by rickstaa** [rssnyder/discord-stock-ticker#198]
@rssnyder now that most of my PRs, except https://github.com/rssnyder/discord-stock-ticker/pull/193 are merged it would be great to create a new release so that people can use the Magic Eden floor price ticker from the release. @rssnyder what do you think?

**Comment by rssnyder** [comment]
thanks for all your work here! https://github.com/rssnyder/discord-stock-ticker/releases/tag/3.10.3

**Comment by rssnyder** [comment]
looks like my pat expired in my CI, gotta fix that quick then the binaries will be added

**Comment by rssnyder** [comment]
https://github.com/rssnyder/discord-stock-ticker/releases/tag/v3.10.4

**Comment by rickstaa** [comment]
Amazing thanks!
