### ISSUE TITLE
[BUG] Fetching stock prices from Yahoo does not work

### ISSUE THREAD

**Issue by 1ci** [rssnyder/discord-stock-ticker#206]
![image](https://github.com/rssnyder/discord-stock-ticker/assets/36176445/bae12c61-55ab-4fc3-a20f-6c2a8bae2021)

**Comment by rssnyder** [comment]
This is fixed in the most recent beta.

Full release later today.

https://github.com/rssnyder/discord-stock-ticker/releases/tag/v3.10.7-beta.1

**Comment by rssnyder** [comment]
got distracted
https://github.com/rssnyder/discord-stock-ticker/releases/tag/v3.10.8

**Comment by 1ci** [comment]
It's alright bud. I've been using the beta and it's been working great so far. Thank you!
