### ISSUE TITLE
[NEW STOCK] ETFM (FOMO CORP.)

### ISSUE THREAD

**Issue by RavenWynters** [rssnyder/discord-stock-ticker#23]
Hello,

I would appreciate it if you add our stock symbol to your bot as we find it very useful for our shareholders in our Discord server. The one caveat would be we are changing our ticker symbol fairly soon to possibly IGOT. Thanks in advance!

[FOMO Corp Logo](https://user-images.githubusercontent.com/81161099/111982716-ae354980-8adf-11eb-966c-4642303b697d.png)

**Comment by rssnyder** [comment]
@RavenWynters Is this your stock? https://finance.yahoo.com/quote/ETFM

**Comment by MarketWatcher1** [comment]
That is the one.

**Comment by rssnyder** [comment]
@MarketWatcher1 

https://discord.com/api/oauth2/authorize?client_id=819939500687360071&permissions=0&scope=bot
