### ISSUE TITLE
[NEW STOCK] ETFM (FOMO CORP.)

### ISSUE THREAD

**Issue by MarketWatcher1** [rssnyder/discord-stock-ticker#24]
Hello,

I would appreciate it if you add our stock symbol to your bot as we find it very useful for our shareholders in our Discord server. I am a Moderator over there and we might also be interested in one or two Premium bots. The one caveat would be we are changing our ticker symbol fairly soon to possibly IGOT. Thanks in advance!

**Comment by rssnyder** [comment]
@MarketWatcher1 ref: https://github.com/rssnyder/discord-stock-ticker/issues/23

https://discord.com/api/oauth2/authorize?client_id=819939500687360071&permissions=0&scope=bot

I can change this when your symbol changes, maybe just hit me up again when that happens. 

As for the premium version, please contact me via one of the options on my github profile page.
