### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by coldpumpkin** [rssnyder/discord-stock-ticker#27]
![image](https://user-images.githubusercontent.com/8443880/112872192-fcd27d00-90b7-11eb-8e29-c3ab85cef032.png)

"Watching..." works but the bot's nickname is like that since forever.

**Comment by rssnyder** [comment]
@coldpumpkin 

Is this a public ticker or a self-hosted?

If self hosted, can you share your setup? If docker, share your compose config (if using compose) otherwise please send the options you enabled.

Have you made sure the bot has "change nickname" permissions on your server?

**Comment by coldpumpkin** [comment]
It's a public ticker, we added it from here. I'll check the "change nickname" permission and I'll get back to you, thank you!

**Comment by rssnyder** [comment]
> It's a public ticker, we added it from here. I'll check the "change nickname" permission and I'll get back to you, thank you!

The public tickers can only change the name once an hour, and you must use the activity to watch the price. This is due to discord API limits. 

If you want the name to update faster, you need to self host or subscribe to the premium private offering.

**Comment by coldpumpkin** [comment]
I confirm he has every permission. 1 hour update should be fine, it's just that he's stuck in $210 for a lot of days now. We'll try kicking him and making him rejoin, I'll let you know.

**Comment by rssnyder** [comment]
> I confirm he has every permission. 1 hour update should be fine, it's just that he's stuck in $210 for a lot of days now. We'll try kicking him and making him rejoin, I'll let you know.

Sometimes the names can be cached, I dont have much control over that.

**Comment by coldpumpkin** [comment]
So I tried adding the bot to another server and the name is still in $210. Ok thank you for all your help. Nevertheless let me just make a final question so that I can understand better the problem - cached as in where?

**Comment by coldpumpkin** [comment]
Ok so, I ended up forking your rep and digged around the code and self hosted the bot. The reason why it's probably stuck is because discord isn't liking the constant name changes. I'm using a bot with your code right now and I simply have it updating the nickname instead of the bot username.

**Comment by rssnyder** [comment]
> Ok so, I ended up forking your rep and digged around the code and self hosted the bot. The reason why it's probably stuck is because discord isn't liking the constant name changes. I'm using a bot with your code right now and I simply have it updating the nickname (server) instead of the username (bot).

Ah so maybe I need to just not start the name change job if `SET_USERNAME` is set. Good idea.

**Comment by coldpumpkin** [comment]
> > Ok so, I ended up forking your rep and digged around the code and self hosted the bot. The reason why it's probably stuck is because discord isn't liking the constant name changes. I'm using a bot with your code right now and I simply have it updating the nickname (server) instead of the username (bot).
> 
> Ah so maybe I need to just not start the name change job if `SET_USERNAME` is set. Good idea.

Yea :) and you should have it set by default to avoid messing with discord.

**Comment by rssnyder** [comment]
> > Ah so maybe I need to just not start the name change job if `SET_USERNAME` is set. Good idea.
> 
> Yea :) and you should have it set on your own bots, to avoid messing with discord.

It still won't affect the public bots as those don't use the nickname feature, but will be helpful for people self hosting.

**Comment by rssnyder** [comment]
https://github.com/rssnyder/discord-stock-ticker/pull/28
