### ISSUE TITLE
[BUG] How to install

### ISSUE THREAD

**Issue by VenuxiCloud** [rssnyder/discord-stock-ticker#37]
Hello,

How do I install the bot, I click on the .exe program and its stuck on time="2021-04-24T18:12:03+01:00" level=info msg="Starting api server on 8080..." and where do I enter the bot token and stuff

**Comment by rssnyder** [comment]
@VenuxiCloud You can either set the bot options via environment vars, explained here: https://github.com/rssnyder/discord-stock-ticker#running-in-a-simple-shell

Or, once it is running, you can use the API to add bots, as explained here: https://github.com/rssnyder/discord-stock-ticker#adding-multiple-bots

**Comment by rssnyder** [comment]
@VenuxiCloud as it's been over a week, I am going to close this issue.

In the future, it might be more efficient to reach out via email/discord for more 1:1 support.
