### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YouShouldBuyGME** [rssnyder/discord-stock-ticker#45]
I cannot get the GME ticker to work. I used the website to easily add the bot to my discord server.

**Comment by rssnyder** [comment]
My apologies, that bot was having some issues. It should be fixed now.
![Screenshot from 2021-05-10 09-54-00](https://user-images.githubusercontent.com/7338312/117679208-ae63d400-b175-11eb-9776-23cf2821083f.png)

**Comment by YouShouldBuyGME** [comment]
Awesome thank you so much.
