### ISSUE TITLE
[BUG] curl localhost:9090/tickerboard is providing empty page

### ISSUE THREAD

**Issue by Treawlony** [rssnyder/discord-stock-ticker#73]
**Describe the bug**
When running curl localhost:9090/tickerboard you get only " { } " as result

**To Reproduce**
1. launch a bot ticker using Docker
2. Bot is running on Discord
3. Above command gives that result

**Expected behaviour**
a list of tickers running

**Comment by Treawlony** [comment]
Extra info: taht is the correct port, 8080 is already busy with something else

**Comment by Treawlony** [comment]
I'm currently testing running this:

curl -X POST -H "Content-Type: application/json" --data '{
  "name": "bitcoin",
  "crypto": true,
  "ticker": "btc",
  "set_color": true,
  "currency": "USD",
  "decimals": 3,
  "set_nickname": true,
  "frequency": 10,
  "discord_bot_token": "addkeyhere"
}' localhost:9090/ticker

**Comment by rssnyder** [comment]
@Treawlony yeah so you need to do `curl localhost:9090/ticker` instead, that will give you a list.

For the color changing, see https://github.com/rssnyder/discord-stock-ticker#roles-for-colors

**Comment by Treawlony** [comment]
Got it! I had the page with instruciton opened twice and I mixed ticker with tickerboard. Solved! Thanks!
