### ISSUE TITLE
[Request] Add AXS and SLP to discord ticker

### ISSUE THREAD

**Issue by mooglestiltzkin** [rssnyder/discord-stock-ticker#76]
Hi,

Could you please add for crypto currencies "AXS" and "SLP" to the discord ticker bot.

https://www.coingecko.com/en/coins/axie-infinity
https://www.coingecko.com/en/coins/smooth-love-potion

if you don't know what axie infinity is

https://www.youtube.com/watch?v=zQPyDc88X8o

thx :}

**Comment by rssnyder** [comment]
These tickers already exist, to find them please join the support server, the link is in the readme, join by clicking on the large discord logo.
