### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by matheusturmina** [rssnyder/discord-stock-ticker#88]
**Describe the bug**
When i change the "currency" of an cryptobot, the bot dont get the variation of an crypto on the same currency. It keeps getting the usd variation.

**To Reproduce**
1. add a bot in brl currency
2. look at status, the variation in % match with usd variation

**Expected behaviour**
The bot should get the brl variation

**Comment by rssnyder** [comment]
The math is a little off based on duckduckgo's conversion rate compared to yahoo finance, but everything seems to add up to me.

USD:
![image](https://user-images.githubusercontent.com/7338312/132894212-44dd4f9f-e793-4aa5-908d-a58a871633c5.png)
![image](https://user-images.githubusercontent.com/7338312/132894640-3f4843fb-dae2-457b-b6f9-bb1a8cb60db9.png)

BRL:
![image](https://user-images.githubusercontent.com/7338312/132894291-e7beeafa-c35f-4764-b3d5-ff3a486430db.png)
![image](https://user-images.githubusercontent.com/7338312/132894753-7c61bb5a-ac34-4051-afbd-9027e986898e.png)

![image](https://user-images.githubusercontent.com/7338312/132894360-e72d85d7-8e15-4eca-bf65-24e714e6e0d5.png)
![image](https://user-images.githubusercontent.com/7338312/132894423-7267c2e5-19ab-41e9-bc5b-5e9490755c8c.png)

As the conversion rate is the same for the current price and the price difference, the percent change across currencies is the same, it shouldn't be different for non-USD currencies. 

My test case:
USD:
```json
{
  "name": "cardano",
  "crypto": true,
  "set_color": true,
  "decorator": " ",
  "set_nickname": true,
  "frequency": 3,
  "discord_bot_token": "xxxxxxxxxxxxxxxxxx"
}
```

BRL:
```json
{
  "name": "cardano",
  "crypto": true,
  "set_color": true,
  "decorator": " ",
  "currency": "BRL",
  "set_nickname": true,
  "frequency": 3,
  "discord_bot_token": "xxxxxxxxxxxxxxxxxx"
}
```

**Comment by rssnyder** [comment]
stale
